server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.100.42.147:3306/paylog?serverTimezone=GMT%2B8&characterEncoding=UTF8
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      max-lifetime: 120000
  application:
    name: consume
    main:
      allow-bean-definition-overriding: true
  redis:
    port: 6379
    password: 123456
    host: 47.100.42.147
logging.level.com.lgak.mapper: debug